# ci.yml
name: Build CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install tools
        run: sudo apt-get install podman curl
      - name: build image
        run: ./docker.sh build
      - name: run tests
        run: ./docker.sh test
      - name: start web service
        run: ./docker.sh run
      - name: check web working
        run: sleep 2 && curl http://127.0.0.1:3000
